#!/bin/bash

# SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=muskCorr.out
#SBATCH --error=muskCorr.err


# the name of the sample to process should be passed as the first parameter (e.g cel, then it will correct reads ./CEL/cel_1.fastq and ./CEL/cel_2.fastq
PREF="./${1^^}/${1,,}"
# echo "PREF: $PREF"

# MUSKNAME="${PREF}_musket"
MUSKNAME="${PREF}_TIEM_MEM_TEST"



# COMMAND="./musket/musket -p 18 -omulti $MUSKNAME ${PREF}_1.fastq ${PREF}_2.fastq"
# exec $COMMAND
# printf "\nCOMMAND: $COMMAND \n"


COMMAND="./musket/musket -p 18 -omulti $MUSKNAME ${PREF}_1.fastq ${PREF}_2.fastq"

printf "\nCOMMAND: $COMMAND \n"

RES_FILE_NAME="MUSKET_${1,,}_resources"
/usr/bin/time -o $RES_FILE_NAME -a -v ./musket/musket -p 18 -omulti $MUSKNAME ${PREF}_1.fastq ${PREF}_2.fastq
