#!/bin/bash

# SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=muskCorr.out
#SBATCH --error=muskCorr.err


./racer/RACER ${1^^}/${1,,}_1.fastq ${1^^}/${1,,}_racer_1.fastq 100000000
./racer/RACER ${1^^}/${1,,}_2.fastq ${1^^}/${1,,}_racer_2.fastq 100000000
