#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/ara_racer.out
#SBATCH --error=logs/ara_racer.err

/usr/bin/time -v -o times/ara_racer.log ./SOAPdenovo-63mer all -s sbatch_scripts/ara_racer.conf -K 63 -R -o results/ara_racer/res
