#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/eco_racer.out
#SBATCH --error=logs/eco_racer.err

/usr/bin/time -v -o times/eco_racer.log ./SOAPdenovo-63mer all -s sbatch_scripts/eco_racer.conf -K 63 -R -o results/eco_racer/res
