#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/lux.out
#SBATCH --error=logs/lux.err

/usr/bin/time -v -o times/lux.log ./SOAPdenovo-63mer all -s sbatch_scripts/lux.conf -K 63 -R -o results/lux/res
