#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/ara.out
#SBATCH --error=logs/ara.err

/usr/bin/time -v -o times/ara.log ./SAGE2 \
  -l /home/users-groups/grant_452/plg/alga_tests/algos/SAGE/SAGE2/sbatch_scripts/ara.list \
  -o results/ara \
  -p ara -k 50 -d -s
