#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task

#SBATCH --time=7-0
#SBATCH --get-user-env

#SBATCH --output=logs/cel_musket_2.out
#SBATCH --error=logs/cel_musket_2.err

/usr/bin/time -v -o times/cel_musket_2.log ./SAGE2 \
  -l /home/users-groups/grant_452/plg/alga_tests/algos/SAGE/SAGE2/sbatch_scripts/cel_musket.list \
  -o results/cel_musket_2 \
  -p cel_musket_2 -k 50 -d -s
