#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/h14_musket.out
#SBATCH --error=logs/h14_musket.err

/usr/bin/time -v -o times/h14_musket.log ./SAGE2 \
  -l /home/users-groups/grant_452/plg/alga_tests/algos/SAGE/SAGE2/sbatch_scripts/h14_musket.list \
  -o results/h14_musket \
  -p h14_musket -k 50 -d -s
