#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/lux_musket.out
#SBATCH --error=logs/lux_musket.err

/usr/bin/time -v -o times/lux_musket.log ./SAGE2 \
  -l /home/users-groups/grant_452/plg/alga_tests/algos/SAGE/SAGE2/sbatch_scripts/lux_musket.list \
  -o results/lux_musket \
  -p lux_musket -k 50 -d -s
