#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/chl_racer.out
#SBATCH --error=logs/chl_racer.err


module load python/3.7.0

/usr/bin/time -v -o times/chl_racer.log bin/megahit \
  -1 /home/users-groups/grant_452/plg/alga_tests/data/CHL/chl_racer_1.fastq \
  -2 /home/users-groups/grant_452/plg/alga_tests/data/CHL/chl_racer_2.fastq \
  -t 16 \
  -o results/chl_racer
