#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task	
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=rPLAT.out
#SBATCH --error=rPLAT.err

# the first parameter should be the name of the sample (e.g lux)
# the second parameter should be extension of reads, that is _musket, _trimmed or _trimmed_musket
# the third  parameter should contain a string in which are written all getopts (e.g "--scale=0.66 --threads=16 --retl=4"

#module load plgrid/tools/gcc/4.9.4



name=${1,,}
PLAT_NAME="plat_${name}"
echo "${PLAT_NAME}"
./platanus scaffold -o $PLAT_NAME -c ${PLAT_NAME}_contig.fa -b ${PLAT_NAME}_contigBubble.fa -IP1 ${name}_1.fastq ${name}_2.fastq -t 16 2> ${name}_scaffold.log
