#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/ara.out
#SBATCH --error=logs/ara.err

/usr/bin/time -v -o times/ara.1.log bin/gt readjoiner prefilter \
  -readset results/ara \
  -db /home/users-groups/grant_452/plg/alga_tests/data/ARA/ara_1.fastq:/home/users-groups/grant_452/plg/alga_tests/data/ARA/ara_2.fastq:250

/usr/bin/time -v -o times/ara.2.log bin/gt -j 8 readjoiner overlap \
  -readset results/ara \
  -l 60

/usr/bin/time -v -o times/ara.3.log bin/gt readjoiner assembly -spmfiles 8 -readset results/ara -l 60
