#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/chl.out
#SBATCH --error=logs/chl.err

/usr/bin/time -v -o times/chl.1.log bin/gt readjoiner prefilter \
  -readset results/chl \
  -db /home/users-groups/grant_452/plg/alga_tests/data/CHL/chl_1.fastq:/home/users-groups/grant_452/plg/alga_tests/data/CHL/chl_2.fastq:500

/usr/bin/time -v -o times/chl.2.log bin/gt -j 8 readjoiner overlap \
  -readset results/chl \
  -l 60

/usr/bin/time -v -o times/chl.3.log bin/gt readjoiner assembly -spmfiles 8 -readset results/chl -l 60
