#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/eco.out
#SBATCH --error=logs/eco.err

/usr/bin/time -v -o times/eco.1.log bin/gt readjoiner prefilter \
  -readset results/eco \
  -db /home/users-groups/grant_452/plg/alga_tests/data/ECO/eco_1.fastq:/home/users-groups/grant_452/plg/alga_tests/data/ECO/eco_2.fastq:500

/usr/bin/time -v -o times/eco.2.log bin/gt -j 8 readjoiner overlap \
  -readset results/eco \
  -l 55

/usr/bin/time -v -o times/eco.3.log bin/gt readjoiner assembly -spmfiles 8 -readset results/eco -l 55
