#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/eco_racer.out
#SBATCH --error=logs/eco_racer.err

/usr/bin/time -v -o times/eco_racer.1.log bin/gt readjoiner prefilter \
  -readset results/eco_racer \
  -db /home/users-groups/grant_452/plg/alga_tests/data/ECO/eco_racer_1.fastq:/home/users-groups/grant_452/plg/alga_tests/data/ECO/eco_racer_2.fastq:500

/usr/bin/time -v -o times/eco_racer.2.log bin/gt -j 8 readjoiner overlap \
  -readset results/eco_racer \
  -l 60

/usr/bin/time -v -o times/eco_racer.3.log bin/gt readjoiner assembly -spmfiles 8 -readset results/eco_racer -l 60
