#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/h14.out
#SBATCH --error=logs/h14.err

/usr/bin/time -v -o times/h14.1.log bin/gt readjoiner prefilter \
  -readset results/h14 \
  -db /home/users-groups/grant_452/plg/alga_tests/data/H14/h14_1.fastq:/home/users-groups/grant_452/plg/alga_tests/data/H14/h14_2.fastq:158

/usr/bin/time -v -o times/h14.2.log bin/gt -j 8 readjoiner overlap \
  -readset results/h14 \
  -l 60

/usr/bin/time -v -o times/h14.3.log bin/gt readjoiner assembly -spmfiles 8 -readset results/h14 -l 60
