#!/bin/bash

#SBATCH -p bigmem
# SBATCH --mem=200000

#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=18            # Number of CPU cores per task


#SBATCH --get-user-env

#SBATCH --output=logs/lux_musket.out
#SBATCH --error=logs/lux_musket.err

/usr/bin/time -v -o times/lux_musket.1.log bin/gt readjoiner prefilter \
  -readset results/lux_musket \
  -db /home/users-groups/grant_452/plg/alga_tests/data/LUX/lux_musket_1.fastq:/home/users-groups/grant_452/plg/alga_tests/data/LUX/lux_musket_2.fastq:315

/usr/bin/time -v -o times/lux_musket.2.log bin/gt -j 8 readjoiner overlap \
  -readset results/lux_musket \
  -l 60

/usr/bin/time -v -o times/lux_musket.3.log bin/gt readjoiner assembly -spmfiles 8 -readset results/lux_musket -l 60
